USE SGHotel;

insert into ROOMTYPE (Typeid, TypeName) values (1, 'Single');
insert into ROOMTYPE (Typeid, TypeName) values (2, 'Double');
insert into ROOMTYPE (Typeid, TypeName) values (3, 'Suite');
insert into ROOMTYPE (Typeid, TypeName) values (4, 'Suite Deluxe');
insert into ROOMTYPE (Typeid, TypeName) values (5, 'Budget');
insert into ROOMTYPE (Typeid, TypeName) values (6, 'Penthouse');
insert into ROOMTYPE (Typeid, TypeName) values (7, 'Penthouse Deluxe');
insert into ROOMTYPE (Typeid, TypeName) values (8, 'Penthouse Platinum Deluxe');


insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (1, 1, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (2, 1, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (3, 1, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (4, 1, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (5, 1, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (6, 1, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (7, 1, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (8, 1, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (9, 1, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (10, 1, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (11, 2, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (12, 2, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (13, 2, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (14, 2, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (15, 2, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (16, 2, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (17, 2, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (18, 2, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (19, 2, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (20, 2, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (21, 3, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (22, 3, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (23, 3, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (24, 3, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (25, 3, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (26, 3, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (27, 3, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (28, 3, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (29, 3, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (30, 3, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (31, 4, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (32, 4, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (33, 4, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (34, 4, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (35, 4, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (36, 4, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (37, 4, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (38, 4, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (39, 4, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (40, 4, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (41, 5, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (42, 5, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (43, 5, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (44, 5, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (45, 5, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (46, 5, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (47, 5, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (48, 5, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (49, 5, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (50, 5, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (51, 6, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (52, 6, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (53, 6, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (54, 6, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (55, 6, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (56, 6, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (57, 6, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (58, 6, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (59, 6, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (60, 6, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (61, 7, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (62, 7, 2, 8);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (63, 7, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (64, 7, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (65, 7, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (66, 7, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (67, 7, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (68, 7, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (69, 7, 2, 5);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (70, 7, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (71, 8, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (72, 8, 2, 1);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (73, 8, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (74, 8, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (75, 8, 2, 2);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (76, 8, 2, 7);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (77, 8, 2, 4);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (78, 8, 2, 3);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (79, 8, 2, 6);
insert into ROOMS (RoomNum, FloorNum, MaxOcc, RoomType) values (80, 8, 2, 5);

